# Generated by Django 4.1.6 on 2023-02-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(default='None provided', max_length=250),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
