# Generated by Django 4.1.6 on 2023-02-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lethal', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='weapons',
            field=models.ManyToManyField(to='main_app.weapon'),
        ),
    ]
